locate_device:
  name: Locate Device
  description: Get the current location of a Google Find My device
  fields:
    device_id:
      name: Device ID
      description: The ID of the device to locate
      required: true
      selector:
        text:

play_sound:
  name: Play Sound
  description: Play a sound on a Google Find My device
  fields:
    device_id:
      name: Device ID
      description: The ID of the device to play sound on
      required: true
      selector:
        text:

locate_device_external:
  name: Locate Device (External)
  description: Get current location using external GoogleFindMyTools process (workaround for FCM issues)
  fields:
    device_id:
      name: Device ID
      description: The canonical device ID to locate
      required: true
      selector:
        text:
    device_name:
      name: Device Name
      description: The friendly name of the device (optional)
      required: false
      selector:
        text: